# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5ab156740203ed907fdbb9aa4a861893e93b1026193133ddf078d6e01aecfe9c8ef894467f5e8c53eb54724b3f4e731f04ae07cf9684a002d3c4fa5b4555f729

test:
  secret_key_base: 805870c8eaa803e2f8df8aeb2ec7f99ce5d12cb92fd510fc18cde7700e12ea7d70fd525b88321d54a1a34db6b83be9523d641f1073392414f98e3535878d3a7b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
